name: Deploy Next.js Blog

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - run: yarn
      - run: yarn build
      - name: upload build files
        uses: actions/upload-artifact@v4
        with:
          name: build-app
          path: |
            .next
            public
            package.json
            yarn.lock

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: download build files
        uses: actions/download-artifact@v4
        with:
          name: build-app
      - name: scp build files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: /home/runner/work/nextjs-blog/nextjs-blog/*
          target: /root/apps/nextjs-blog/deploy
      - name: deploy with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e
            cd /root/apps/nextjs-blog
            git pull origin master
            pm2 delete nextjs-blog || true
            rm -rf .next public package.json yarn.lock
            mv deploy/* .
            pm2 start yarn --name "nextjs-blog" -- start
            pm2 save